namespace : default

app:
  replicas : 1
  env: dev
  name: authorization-service
  container:
    image:
      repository: ishara007/authorization-service
      tag: v3
    imagePullPolicy: Always
    ports:
      containerPort: 9002
  computerc:
    limits:
      cpu: "0.2"
      memory: 500Mi
    requests:
      cpu: "0.2"
      memory: 500Mi

## ---------------------------- Service ----------------------------##

service:
  name: authorization-service
  type: ClusterIP
  ports:
    port: 9002
    targetPort: 9002

## ---------------------------- Role & RoleBindings ----------------------------##

role:
  name: devRole

roleBinding:
  name: devRoleBinding