app:
  replicas : 1
  env: dev
  container:
    image: ishara007/authorization-service:latest
  computerc:
    limits:
      cpu: "0.2"
      memory: 500Mi
    requests:
      cpu: "0.2"
      memory: 500Mi