server:
  port: 9001

spring:
  application:
    name: MAIN-SERVICE
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9002/.well-known/jwks.json



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#key.location: keys/keystore.jks
