services:
  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - "9042:9042"
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces"
        ]
      interval: 15s
      timeout: 10s
      retries: 10
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./UserParlourDump.cql:/UserParlourDump.cql
      - ./ArticleParlourDump.cql:/ArticleParlourDump.cql
      - ./StreamParlourDump.cql:/StreamParlourDump.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /UserParlourDump.cql && cqlsh cassandra -f /ArticleParlourDump.cql && cqlsh cassandra -f /StreamParlourDump.cql"