server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: article-service
  data:
    cassandra:
      keyspace-name: parlour
      contact-points: 127.0.0.1
#      contact-points: cassandra.us-east-1.amazonaws.com
      port: 9042
#      port: 9142
      schema-action: CREATE_IF_NOT_EXISTS
      username: null
#      username: ishara.d.wijesinghe@gmail.com-at-317082675872
#      password: BUvnF0tjIJiLkPLrNFKTI60FoGDZFnvePD4M+rWG2BY=
      #      ssl: true
      #      request:
      #        consistency: local_quorum
      password: null
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9002/.well-known/jwks.json
  cloud:
    cloud:
      kubernetes:
        enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

amazon:
  aws:
    region: us-east-1
    secret-key: ""
    access-key: ""

cloud:
  provider: AWS

aws:
  bucket:
    user-image-upload: dev-parlour-user-images