spring:
  data:
    cassandra:
      keyspace-name: parlour
      contact-points: host.minikube.internal
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorization-service.default.svc.cluster.local:9002/.well-known/jwks.json
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
