server:
  port: 9191

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

spring:
  application:
    name: API-GATEWAY
  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: MAIN-SERVICE
          uri: lb://MAIN-SERVICE/
          predicates:
            - Path=/main/**
          filters:
            TokenRelay=
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: gateway-client-id
            client-secret: my-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9191/login/oauth2/code/{registrationId}"
            scope: openid, message.read
        provider:
          my-provider:
            issuer-uri: http://127.0.0.1:9002

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/