server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: gateway-client-id
            client-secret: my-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://API-GATEWAY:9191/login/oauth2/code/{registrationId}"
            scope: openid, message.read
        provider:
          my-provider:
            issuer-uri: http://localhost:9002
  cloud:
    gateway:
      routes:
        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/authentication/**
          filters:
            TokenRelay=
        - id: MAIN-SERVICE
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/main/**
          filters:
            TokenRelay=

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/