namespace : default

## ---------------------------- Deployment ----------------------------##

app:
  replicas : 1
  env: dev
  name: user-service
  serviceAccount: user-service-name
  container:
    image:
      repository: ishara007/user-service
      tag: v1
    imagePullPolicy: Always
    ports:
      containerPort: 9002
  computerc:
    limits:
      cpu: "0.2"
      memory: 500Mi
    requests:
      cpu: "0.2"
      memory: 500Mi

## ---------------------------- Service ----------------------------##

service:
  name: user-service
  type: ClusterIP
  ports:
    port: 9002
    targetPort: 9002

## ---------------------------- Role & RoleBindings ----------------------------##

role:
  name: devUserRole

roleBinding:
  name: devUserRoleBinding

## ---------------------------- Config Map ----------------------------##

config:
  metadata:
    name: cassandra-db-host
  data:
    cassandra_host_dns: host.minikube.internal