{{/* *************-------Create config map-------************* */}}
{{- if (.Values.fluentBit.enabled)}}  {{/* Run only if fluentbit enabled */}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-for-fluent-bit.fullname" . }}
  namespace: {{ include "aws-for-fluent-bit.namespace" . }}
  labels:
    {{- include "aws-for-fluent-bit.labels" . | nindent 4 }}
data:
  parsers.conf: |-

  fluent-bit.conf: |
    [SERVICE]
{{- range .Values.service.parsersFiles }}
        Parsers_File {{ . }}
{{- end }}

    [INPUT]
        Name              tail
        Tag               {{ .Values.input.tag }}
        Path              {{ .Values.input.path }}
        DB                {{ .Values.input.db }}
        Parser            {{ .Values.input.parser }}
        Docker_Mode       {{ .Values.input.dockerMode }}
        Mem_Buf_Limit     {{ .Values.input.memBufLimit }}
        Skip_Long_Lines   {{ .Values.input.skipLongLines }}
        Refresh_Interval  {{ .Values.input.refreshInterval }}

    [FILTER]
        Name                kubernetes
        Match               {{ .Values.filter.match }}
        Kube_URL            {{ .Values.filter.kubeURL }}
        Merge_Log           {{ .Values.filter.mergeLog }}
        {{- if .Values.filter.mergeLogKey }}
        Merge_Log_Key       {{ .Values.filter.mergeLogKey }}
        {{- end }}
        Keep_Log            {{ .Values.filter.keepLog }}
        K8S-Logging.Parser  {{ .Values.filter.k8sLoggingParser }}
        K8S-Logging.Exclude {{ .Values.filter.k8sLoggingExclude }}
        Buffer_Size         {{ .Values.filter.bufferSize }}

{{/* ********------CloudWatch output configuration------******** */}}
{{- if .Values.cloudWatch.enabled }}
    [OUTPUT]
        Name                  cloudwatch
        Match                 {{ .Values.cloudWatch.match }}
        region                {{ .Values.cloudWatch.region }}
        log_group_name        {{ .Values.cloudWatch.logGroupName }}
        {{- if .Values.cloudWatch.logStreamName }}
        log_stream_name       {{ .Values.cloudWatch.logStreamName }}
        {{- end }}
        {{- if .Values.cloudWatch.logStreamPrefix }}
        log_stream_prefix     {{ .Values.cloudWatch.logStreamPrefix }}
        {{- end }}
        {{- if .Values.cloudWatch.logKey }}
        log_key               {{ .Values.cloudWatch.logKey }}
        {{- end }}
        {{- if .Values.cloudWatch.logFormat }}
        log_format            {{ .Values.cloudWatch.logFormat }}
        {{- end }}
        {{- if .Values.cloudWatch.logRetentionDays }}
        log_retention_days    {{ .Values.cloudWatch.logRetentionDays }}
        {{- end }}
        {{- if .Values.cloudWatch.roleArn }}
        role_arn              {{ .Values.cloudWatch.roleArn }}
        {{- end }}
        {{- if .Values.cloudWatch.autoCreateGroup }}
        auto_create_group     {{ .Values.cloudWatch.autoCreateGroup }}
        {{- end }}
        {{- if .Values.cloudWatch.endpoint }}
        endpoint              {{ .Values.cloudWatch.endpoint }}
        {{- end }}
        {{- if .Values.cloudWatch.credentialsEndpoint }}
        credentials_endpoint  {{ toJson .Values.cloudWatch.credentialsEndpoint }}
        {{- end -}}
{{- end }}

{{/* ********------S3 output configuration------******** */}}
{{- if .Values.s3.enabled }}
    [OUTPUT]
        Name                  s3
        Match                 {{ .Values.cloudWatch.match }}
        region                {{ .Values.s3.region }}
        bucket                {{ .Values.s3.bucket }}
    {{- if .Values.s3.logKey }}
        log_key               {{ .Values.s3.logKey }}
    {{- end }}
    {{- if .Values.s3.use_put_object }}
        use_put_object        {{ .Values.s3.use_put_object }}
    {{- end }}
    {{- if .Values.s3.s3_key_format }}
        s3_key_format    {{ .Values.s3.s3_key_format }}
    {{- end }}
    {{- if .Values.s3.s3_key_format_tag_delimiters }}
        s3_key_format_tag_delimiters              {{ .Values.s3.s3_key_format_tag_delimiters }}
    {{- end }}
    {{- if .Values.s3.total_file_size }}
        total_file_size     {{ .Values.s3.total_file_size }}
    {{- end }}
    {{- if .Values.s3.upload_timeout }}
        upload_timeout              {{ .Values.s3.upload_timeout }}
    {{- end }}
{{- end }}

{{/* ********------Kinesis firehose output configuration------******** */}}
{{- if .Values.firehose.enabled }}
    [OUTPUT]
        Name            firehose
        Match           {{ .Values.firehose.match }}
        region          {{ .Values.firehose.region }}
        delivery_stream {{ .Values.firehose.deliveryStream }}
        {{- if .Values.firehose.dataKeys }}
        data_keys       {{ .Values.firehose.dataKeys }}
        {{- end }}
        {{- if .Values.firehose.roleArn }}
        role_arn        {{ .Values.firehose.roleArn }}
        {{- end }}
        {{- if .Values.firehose.endpoint }}
        endpoint        {{ .Values.firehose.endpoint }}
        {{- end }}
        {{- if .Values.firehose.timeKey }}
        time_key        {{ .Values.firehose.timeKey }}
        {{- end }}
        {{- if .Values.firehose.timeKeyFormat }}
        time_key_format {{ .Values.firehose.timeKeyFormat }}
        {{- end -}}
{{- end }}

{{/* ********------Kinesis output configuration------******** */}}
{{- if .Values.kinesis.enabled }}
    [OUTPUT]
        Name            kinesis
        Match           {{ .Values.kinesis.match }}
        region          {{ .Values.kinesis.region }}
        stream          {{ .Values.kinesis.stream }}
        {{- if .Values.kinesis.partitionKey }}
        partition_key   {{ .Values.kinesis.partitionKey }}
        {{- end }}
        {{- if .Values.kinesis.appendNewline }}
        append_newline  {{ .Values.kinesis.appendNewline }}
        {{- end }}
        {{- if .Values.kinesis.replaceDots }}
        replace_dots    {{ .Values.kinesis.replaceDots }}
        {{- end }}
        {{- if .Values.kinesis.dataKeys }}
        data_keys       {{ .Values.kinesis.dataKeys }}
        {{- end }}
        {{- if .Values.kinesis.roleArn }}
        role_arn        {{ .Values.kinesis.roleArn }}
        {{- end }}
        {{- if .Values.kinesis.endpoint }}
        endpoint        {{ .Values.kinesis.endpoint }}
        {{- end }}
        {{- if .Values.kinesis.stsEndpoint }}
        sts_endpoint    {{ .Values.kinesis.stsEndpoint }}
        {{- end }}
        {{- if .Values.kinesis.timeKey }}
        time_key        {{ .Values.kinesis.timeKey }}
        {{- end }}
        {{- if .Values.kinesis.timeKeyFormat }}
        time_key_format {{ .Values.kinesis.timeKeyFormat }}
        {{- end }}
        {{- if .Values.kinesis.aggregation }}
        aggregation     {{ .Values.kinesis.aggregation }}
        {{- end }}
        {{- if .Values.kinesis.compression }}
        compression     {{ .Values.kinesis.compression }}
        {{- end }}
        {{- if .Values.kinesis.experimental.concurrency }}
        experimental_concurrency          {{ .Values.kinesis.experimental.concurrency }}
        {{- end }}
        {{- if .Values.kinesis.experimental.concurrencyRetries }}
        experimental_concurrency_retries  {{ .Values.kinesis.experimental.concurrencyRetries }}
        {{- end -}}
{{- end }}

{{/* ********------Elastic search output configuration------******** */}}
{{- if .Values.elasticsearch.enabled }}
    [OUTPUT]
        Name            es
        Match           {{ .Values.elasticsearch.match }}
        AWS_Region      {{ .Values.elasticsearch.awsRegion }}
        AWS_Auth        {{ .Values.elasticsearch.awsAuth }}
        {{- if .Values.elasticsearch.host }}
        Host            {{ .Values.elasticsearch.host }}
        {{- end }}
        {{- if .Values.elasticsearch.port }}
        Port            {{ .Values.elasticsearch.port }}
        {{- end }}
        {{- if .Values.elasticsearch.tls }}
        TLS             {{ .Values.elasticsearch.tls }}
        {{- end }}
        {{- if .Values.elasticsearch.retryLimit }}
        Retry_Limit     {{ .Values.elasticsearch.retryLimit }}
        {{- end }}
        {{- if .Values.elasticsearch.replaceDots }}
        Replace_Dots    {{ .Values.elasticsearch.replaceDots }}
        {{- end -}}
        {{- if .Values.elasticsearch.suppressTypeName }}
        Suppress_Type_Name    {{ .Values.elasticsearch.suppressTypeName }}
        {{- end -}}
{{- end }}

