namespace : default

## ---------------------------- Deployment ----------------------------##

app:
  ## General cluster information like replica count / environment and name of the deployment
  replicas : 1
  env: dev
  name: article-service
  serviceAccount: article-service-name

  ## Container configurations -->  like image / tag / image pull policy / ports
  container:
    image:
      repository: ishara007/article-service
      tag: v1
    imagePullPolicy: Always
    ports:
      containerPort: 9001

    ## Deployment compute resources
    computerc:
      limits:
        cpu: "0.2"
        memory: 500Mi
      requests:
        cpu: "0.2"
        memory: 500Mi

## ---------------------------- Service ----------------------------##

service:
  ## Service general details
  name: article-service
  type: ClusterIP

  ## Service port details
  ports:
    port: 9001
    targetPort: 9001

## ---------------------------- Role & RoleBindings ----------------------------##

## Role name
role:
  name: devArticleRole

## Role binding name
roleBinding:
  name: devArticleRoleBinding

## ---------------------------- Config Map ----------------------------##

config:
  metadata:
    name: cassandra-db-host
  data:
    cassandra_host_dns: host.minikube.internal