app:
  replicas : 1
  env: dev
  name: article-service
  container:
    image:
      repository: ishara007/article-service
      tag: latest
    imagePullPolicy: Always
    ports:
      containerPort: 9001
  computerc:
    limits:
      cpu: "0.2"
      memory: 500Mi
    requests:
      cpu: "0.2"
      memory: 500Mi

## ---------------------------- Service ----------------------------##

service:
  name: article-service
  type: ClusterIp
  ports:
    port: 9001
    targetPort: 9001