server:
  port: 9002

spring:
  application:
    name: AUTHENTICATION-SERVICE
  data:
    cassandra:
      keyspaceName: parlour
      contactPoints: localhost
      port: 9042
      schemaAction: CREATE_IF_NOT_EXISTS

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


