spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorization-service-svc.default.svc.cluster.local:9002/.well-known/jwks.json

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka