server:
  port: 9191

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: api-gateway
  cloud:
    kubernetes:
      enabled: false
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: STREAM-SERVICE
          uri: lb://stream-service/
          predicates:
            - Path=/stream/**
          filters:
            TokenRelay=
        - id: ARTICLE-SERVICE
          uri: lb://article-service/
          predicates:
            - Path=/article/**
          filters:
            TokenRelay=
        - id: AUTHORIZATION-SERVICE
          uri: lb://authorization-service/
          predicates:
            - Path=/authentication/**, /userutil/**
          filters:
            TokenRelay=
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9002/.well-known/jwks.json

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

