{{- $role:= (lookup "rbac.authorization.k8s.io/v1" "Role" .Values.namespace .Values.role.name)}}
{{- if not $role}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.role.name}}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets", "serviceaccounts", "namespaces"]
    verbs: ["get", "list", "watch", "create", "delete", "deletecollection", "patch", "update"]
{{- end }}