{{- $roleBinding:= (lookup "rbac.authorization.k8s.io/v1" "RoleBinding" .Values.namespace .Values.roleBinding.name)}}
{{- if not $roleBinding}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Values.roleBinding.name}}
  namespace: {{.Values.namespace}}
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: {{.Values.role.name}}
  apiGroup: ""
{{- end }}