{{- $serviceAccount:= (lookup "v1" "ServiceAccount" .Values.namespace .Values.roleBinding.name)}}
{{- if not $serviceAccount}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.app.serviceAccount}}
  namespace: {{.Values.namespace}}
{{- end }}