apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-service
  labels:
    app: article-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article-service
  template:
    metadata:
      labels:
        app: article-service
    spec:
      containers:
        - name: article-service
          image: ishara007/article-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: article-service-svc
spec:
  ports:
    - port: 80
      targetPort: 9001
      protocol: TCP
  selector:
    app: article-service
