apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-service
  labels:
    app: authorization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-service
  template:
    metadata:
      labels:
        app: authorization-service
    spec:
      containers:
        - name: authorization-service
          image: ishara007/authorization-service:v3
          env:
            - name: SPRING_DATA_CASSANDRA_CONTACT-POINTS
              value: host.minikube.internal
          imagePullPolicy: Always
          ports:
            - containerPort: 9002

---
apiVersion: v1
kind: Service
metadata:
  name: authorization-service
spec:
  type: NodePort
  ports:
    - port: 9002
      targetPort: 9002
      nodePort: 30001
      protocol: TCP
  selector:
    app: authorization-service
