server:
  port: 9004

spring:
  application:
    name: notification-service
  cloud:
    kubernetes:
      enabled: false
  mail:
    host: smtp.gmail.com
    username: ishara.d.wijesinghe@gmail.com
    password: qkoqyyqpaytmfvsq
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

application:
  emailProvide: Google
  authserver: http://127.0.0.1:9003