spring:
  data:
    cassandra:
      keyspace-name: parlour
      contact-points: cassandra.us-east-1.amazonaws.com
      port: 9142
      schema-action: CREATE_IF_NOT_EXISTS
      username: null
      password: null
      ssl: true
      request:
        consistency: local_quorum


