namespace : default

## ---------------------------- Deployment ----------------------------##

app:
  ## General cluster information like replica count / environment and name of the deployment
  replicas : 1
  env: dev
  name: api-gateway

  ## Container configurations -->  like image / tag / image pull policy / ports
  container:
    image:
      repository: ishara007/api-gateway
      tag: v3
    imagePullPolicy: Always
    ports:
      containerPort: 9191

  ## Deployment compute resources
  computerc:
    limits:
      cpu: "0.2"
      memory: 500Mi
    requests:
      cpu: "0.2"
      memory: 500Mi

## ---------------------------- Service ----------------------------##

service:
  ## Service general details
  name: api-gateway
  type: LoadBalancer

  ## Service port details
  ports:
    port: 9191
    targetPort: 9191

## ---------------------------- Role & RoleBindings ----------------------------##

## Role name
role:
  name: devRole

## Role binding name
roleBinding:
  name: devRoleBinding
