apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: "eureka"
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: ishara007/service-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address






{{/*apiVersion: apps/v1*/}}
{{/*kind: Deployment*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "service-registry.fullname" . }}*/}}
{{/*  labels:*/}}
{{/*    {{- include "service-registry.labels" . | nindent 4 }}*/}}
{{/*spec:*/}}
{{/*  {{- if not .Values.autoscaling.enabled }}*/}}
{{/*  replicas: {{ .Values.replicaCount }}*/}}
{{/*  {{- end }}*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      {{- include "service-registry.selectorLabels" . | nindent 6 }}*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      {{- with .Values.podAnnotations }}*/}}
{{/*      annotations:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      labels:*/}}
{{/*        {{- include "service-registry.selectorLabels" . | nindent 8 }}*/}}
{{/*    spec:*/}}
{{/*      {{- with .Values.imagePullSecrets }}*/}}
{{/*      imagePullSecrets:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      serviceAccountName: {{ include "service-registry.serviceAccountName" . }}*/}}
{{/*      securityContext:*/}}
{{/*        {{- toYaml .Values.podSecurityContext | nindent 8 }}*/}}
{{/*      containers:*/}}
{{/*        - name: {{ .Chart.Name }}*/}}
{{/*          securityContext:*/}}
{{/*            {{- toYaml .Values.securityContext | nindent 12 }}*/}}
{{/*          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"*/}}
{{/*          imagePullPolicy: {{ .Values.image.pullPolicy }}*/}}
{{/*          ports:*/}}
{{/*            - name: http*/}}
{{/*              containerPort: {{ .Values.service.port }}*/}}
{{/*              protocol: TCP*/}}
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          resources:*/}}
{{/*            {{- toYaml .Values.resources | nindent 12 }}*/}}
{{/*      {{- with .Values.nodeSelector }}*/}}
{{/*      nodeSelector:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      {{- with .Values.affinity }}*/}}
{{/*      affinity:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      {{- with .Values.tolerations }}*/}}
{{/*      tolerations:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
