apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
  labels:
    app: main-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
        - name: main-service
          image: ishara007/main-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: main-service-svc
spec:
  ports:
    - targetPort: 9001
      port: 80
  selector:
    app: main-service
