apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app.name}}
  labels:
    app: {{.Values.app.name}}
    env: {{.Values.app.env}}
spec:
  replicas: {{.Values.app.replicas}}
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    spec:
      containers:
        - name: {{.Values.app.name}}
          image: {{.Values.app.container.image.repository}}:{{.Values.app.container.image.tag}}
          env:
            - name: SPRING_DATA_CASSANDRA_CONTACT-POINTS
              #value: host.minikube.internal
              value: vpce-0989bcb4da35676c5-nyaj0jk5.vpce-svc-0eaac7976cc56cdb0.us-east-1.vpce.amazonaws.com
          imagePullPolicy: {{.Values.app.container.imagePullPolicy}}
          ports:
            - containerPort: {{.Values.app.container.ports.containerPort}}
          resources:
            {{- toYaml .Values.app.computerc | nindent 12}}
