apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.ports.port}}
      targetPort: {{.Values.service.ports.targetPort}}
      protocol: TCP
  selector:
    app: {{.Values.app.name}}
