apiVersion: v1
kind: Service
metadata:
  name: authorization-service-svc
spec:
  type: LoadBalancer
  ports:
    - port: 9002
      targetPort: 9002
      protocol: TCP
  selector:
    app: authorization-service
