name: Api-Gateway-Deployment

on:
  workflow_dispatch: {}

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@v1.0.4
      with:
        aws-access-key-id: AKIAU6EWUZ3DZQKLHNMD
        aws-secret-access-key: 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
        aws-region: us-east-1
        cluster-name: eks
        config-files: Deployment/HelmCharts/api-gateway/environment/values.yaml
        chart-path: Deployment/HelmCharts/api-gateway
        namespace: default
        name: api-gateway
