name: Dev-Api-Gateway-Deployment

on:
  workflow_dispatch: {}

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: kubeconfing
        run: |
          aws eks --region us-east-1 update-kubeconfig --name eks
          KUBE_CONFIG_DATA=$(cat ~/.kube/config | base64)
          echo "KUBE_CONFIG_DATA" >> $GITHUB_ENV

      - name: Read exported variable
        run: |
          echo "KUBE_CONFIG_DATA"
          echo "${{ env.KUBE_CONFIG_DATA }}"

      - name: helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
        with:
          plugins: "https://github.com/jkroepke/helm-secrets" # optional
          command: helm upgrade api-gateway Deployment/HelmCharts/api-gateway/ --values Deployment/HelmCharts/api-gateway/environment/values.yaml --set app.container.image.tag=v1
