name: "Infrastructure Destroy"

on:
  workflow_dispatch:
    inputs:
      # Working directory input from user. --> Dev / Prod / Stage
      resource:
        type: choice
        description: Choose the resource
        options:
          - Deployment/Terraform/aws/environment/dev/infrastructure
      # Terraform action you want to perform --> Terraform apply or delete
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
          - Terraform_destroy

jobs:
  #Terraform infrastructure destroy
  terraform_destroy:
    name: "Terraform_destroy"
    if: ${{ github.event.inputs.action == 'Terraform_destroy' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.resource }}
    steps:
      #Checkout project
      - name: Checkout
        uses: actions/checkout@v2

      #Setup terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      #Call terraform init
      - name: Terraform Init
        id: init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      #Call terraform destroy
      - name: Terraform Destroy
        id: destroy
        working-directory: ${{ github.event.inputs.resource }}
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1