name: "Infrastructure Deployment"

on:
  workflow_dispatch:
    inputs:
      # Working directory input from user. --> Dev / Prod / Stage
      resource:
        type: choice
        description: Choose the resource
        options:
          - Deployment/Terraform/aws/environment/dev/infrastructure
      # Terraform action you want to perform --> Terraform apply or delete
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
          - Terraform_apply
          - Terraform_destroy

jobs:
  #Terraform infrastructure apply
  terraform_apply:
    name: "Terraform_apply"
    if: ${{ github.event.inputs.action == 'Terraform_apply' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.resource }}
    steps:

      #Checkout project
      - name: Checkout
        uses: actions/checkout@v2

      #Setup terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      #Call terraform init
      - name: Terraform Init
        id: init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      #Call terraform validate
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      #Call terraform apply
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1