name: "Manually Microservices Deploying Process"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Micro Service To Deploy'
        type: choice
        options:
          - Api-GW
          - Auth-Server
          - Stream-Server
          - Article-Server
          - Notification-Server

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      #Deployment of API GW
      - name: Deploy Api Gateway
        if: ${{ github.event.inputs.action == 'Api-GW' }}
        uses: ./.github/actions/services/api-gateway
        with:
          AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      #Deployment of Authorization Service
      - name: Deploy Authorization Service
        if: ${{ github.event.inputs.action == 'Auth-Server' }}
        uses: ./.github/actions/services/authorization-service
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      #Deployment of Stream Server
      - name: Deploy Stream Server
        if: ${{ github.event.inputs.action == 'Stream-Server' }}
        uses: ./.github/actions/services/stream-service
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      #Deployment of Article Server
      - name: Deploy Article Server
        if: ${{ github.event.inputs.action == 'Article-Server' }}
        uses: ./.github/actions/services/article-service
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      #Deployment of Notification Server
      - name: Deploy Notification Server
        if: ${{ github.event.inputs.action == 'Notification-Server' }}
        uses: ./.github/actions/services/notification-service
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}