app:
  replicas : 1
  env: dev
  name: stream-service
  container:
    image:
      repository: ishara007/stream-service
      tag: latest
    imagePullPolicy: Always
    ports:
      containerPort: 9003
  computerc:
    limits:
      cpu: "0.2"
      memory: 500Mi
    requests:
      cpu: "0.2"
      memory: 500Mi

## ---------------------------- Service ----------------------------##

service:
  name: stream-service
  type: ClusterIp
  ports:
    port: 9003
    targetPort: 9003